
GET http://localhost:1993/

HTTP/1.1 200 OK
content-type: text/plain;charset=UTF-8
vary: Accept-Encoding
content-length: 20
date: Tue, 15 Oct 2024 11:34:13 GMT

Hello world at root!

### GET ALL ITEMS

GET http://localhost:1993/items

HTTP/1.1 200 OK
content-type: text/plain;charset=UTF-8
vary: Accept-Encoding
content-length: 21
date: Tue, 15 Oct 2024 11:34:50 GMT

Retrieving all items.

### GET A SINGLE ITEMS

GET http://localhost:1993/items/2

HTTP/1.1 200 OK
content-type: text/plain;charset=UTF-8
vary: Accept-Encoding
content-length: 25
date: Tue, 15 Oct 2024 11:35:07 GMT

Retrieving item with id 1

### POST
POST http://localhost:1993/items
content-type: application/json

{
    "name": "sample",
    "id": "4"
}

### RESPONSE :
HTTP/1.1 200 OK
content-type: text/plain;charset=UTF-8
vary: Accept-Encoding
content-encoding: gzip
content-length: 95
date: Tue, 15 Oct 2024 11:38:00 GMT

Posting an item. Data: {"name":"sample","time":"Wed, 21 Oct 2024 18:27:50 GMT"}