name: 'my-app'

services:

  db:
    image: postgres
    restart: unless-stopped
    ports:
      - 5432:5432

  app:
    build: app
    image: my-app
    restart: unless-stopped
    volumes:
      - ./app:/app
    depends_on:
      - db
    ports:
      - 1993:1993